---
- hosts: 172.31.47.150
  become: yes
  tasks:
  - name: excute linux commnd directly
    command: hostname -f
    register: myresult
  
  - name: i want to display first task result
    debug:
      msg: "{{myresult}}"