---
- hosts: 172.31.47.150
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: create folder
    file:
        path: /home/ubuntu/myfolder
        state: directory

  - name: i want to copy files
    copy:
        src: mystaticfile
        dest: /home/ubuntu/mystaticfile.txt

  - name: install apachc2
    apt:
       name: apachc2
       state: present
