---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want install java on ubuntu
    apt:
       name: "{{myjavapackonubuntu}}"
       state: present
    when: ansible_os _family=="Debian"

  - name: i want to install java on RedHat nodes 
    yum:
       name: "{{myjavapackonRedHat}}" 
       state: present
    when: ansible_os_family=="RedHat"